version: 2019.0.{build}
pull_requests:
  do_not_increment_build_number: true
max_jobs: 1
image: WMF 5
environment:
  GitHubKey:
    secure: bGxozoCJoYVeoQCF1W+tLhKbjvFoyr7zGcc2A57UiP356gpE7k8/fhqH6NPi8eQ2
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
deploy_script:
- ps: >-
    . .\ci\Invoke-Process.ps1

    . .\scripts\Optimise-Images.ps1
    
    . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'main' of.*/

only_commits:
  files:
    - icons/*
